name: WongSmileClub
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0

targets:
  WongSmileClub:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - WongSmileClub
    resources:
      - WongSmileClub/Resources
      - WongSmileClub/Assets.xcassets
    info:
      path: WongSmileClub/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.wongsmileclub
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  WongSmileClubTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - WongSmileClubTests
    dependencies:
      - target: WongSmileClub

  WongSmileClubUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - WongSmileClubUITests
    dependencies:
      - target: WongSmileClub
